### PR TITLE
podsspecs added, twitter added

### PR DESCRIPTION
**Pull request by ijameelkhan**

### CODE REVIEW

**Comment by ijameelkhan** [comment]
I have added twitter and only added for pulling user info. havent dont the avatar etc , can you do it ? and probbably clean up the code a bit and push specs repo.

**Comment by jonasman** [comment]
I will have a look at this when i get some time!
Thanks for the pull request :)

**Comment by jonasman** [comment]
I have added the Twitter now and implemented the avatar and background image too

**Comment by ijameelkhan** [comment]
ok perfect!

**Pull request merged**
